on:
  push:
    branches: [ "*" ]

jobs:
  deploydocker:
    defaults:
      run:
        shell: bash
        working-directory: dashboard
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: Jemila-Abdulai/software-engineering-2/.github/workflows/dashboard.yml

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Build the Docker image
        run: docker build . --tag samreece/sweng2-coursework:$(date +%s)

