on:
  push:
    branches:
      - '*'

jobs:
  deploydocker:
    defaults:
      run:
        shell: bash
        working-directory: dashboard
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Get repo version
        run: set TAG=$(python ../util/what-version-are-we.py)

      - name: Checking out most recent tag
        run: git checkout tags/${{ env.TAG }}

      - name: Install dependencies
        run: npm install

      - name: Lint and test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Build the Docker image
        run: docker build . --tag samreece/sweng2-coursework:${{ env.TAG }}

